### ISSUE TITLE
i2b2 set up fails when database user accounts passwords are changed

### ISSUE THREAD

**Issue by rchulyadyo** [waghsk/i2b2-quickstart#11]
Current docker image for i2b2 Wildfly (i2b2-wildfly) does not properly make use of DS_PASSWORD environment variable and fails to connect to data sources when the database password for i2b2* user accounts are changed to non-default ones.

**Steps to replicate:**
1. Run i2b2-pg, i2b2-wildfly and i2b2-web containers with `docker-compose up` command with following `docker-compose.yml`.
```yaml
version: '3.2'
services:
    i2b2-pg:
        image: i2b2/i2b2-pg:p1
        container_name: i2b2-pg
        ports:
            - "5432:5432"

    i2b2-wildfly:
        image: i2b2/i2b2-wildfly:0.1
        ports:
            - "8080:8080"
            - "9900:9900"

    i2b2-web:
        container_name: i2b2-web
        image: i2b2/i2b2-web:p1
        command: /run-httpd.sh localhost
        ports:
            - "80:80"
            - "443:443"
```
2. Connect to i2b2-pg and alter database user passwords.
```sql
ALTER USER i2b2 WITH PASSWORD 'newpass' ;
ALTER USER i2b2demodata WITH PASSWORD 'newpass' ;
ALTER USER i2b2hive WITH PASSWORD 'newpass' ;
ALTER USER i2b2imdata WITH PASSWORD 'newpass' ;
ALTER USER i2b2metadata WITH PASSWORD 'newpass' ;
ALTER USER i2b2pm WITH PASSWORD 'newpass' ;
ALTER USER i2b2workdata WITH PASSWORD 'newpass' ;`
```
3.  Update `docker-compose.yml` and run `docker-compose up` command.
```yaml
version: '3.2'
services:
    i2b2-pg:
        image: i2b2/i2b2-pg:p1
        container_name: i2b2-pg
        ports:
            - "5432:5432"

    i2b2-wildfly:
        image: i2b2/i2b2-wildfly:0.1
        environment:
            - DS_PASS=newpass
        ports:
            - "8080:8080"
            - "9900:9900"

    i2b2-web:
        container_name: i2b2-web
        image: i2b2/i2b2-web:p1
        command: /run-httpd.sh localhost
        ports:
            - "80:80"
            - "443:443"
```
4. Browse http://localhost/webclient. You can see following error in Wildfly log.
```
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "i2b2pm"
i2b2-wildfly_1  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:398)
i2b2-wildfly_1  | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:173)
i2b2-wildfly_1  | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
i2b2-wildfly_1  | 	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
i2b2-wildfly_1  | 	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
i2b2-wildfly_1  | 	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
i2b2-wildfly_1  | 	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
i2b2-wildfly_1  | 	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
i2b2-wildfly_1  | 	at org.postgresql.Driver.makeConnection(Driver.java:393)
i2b2-wildfly_1  | 	at org.postgresql.Driver.connect(Driver.java:267)
i2b2-wildfly_1  | 	at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:319)
i2b2-wildfly_1  | 	... 21 more
```

**Proposed fix:**
Instead of relying on `sed` command to update data source configuration files, we can use environment variable in `standalone.xml` file to define data sources. One drawback of this is we will need to maintain database type specific `standalone.xml` if we use database type specific datasource properties.
